### ISSUE TITLE
UMA introspection configration in IS 6.0 is incorrect

### ISSUE THREAD

**Issue by hwupathum** [wso2/docs-is#3635]
The configuration to obtain UMA related information in the introspection which is stated in [UMA docs for IS 6.0](https://is.docs.wso2.com/en/latest/guides/access-delegation/uma/#token-introspection) has been removed in https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/1379.

The new configuration is
```toml
[event.default_listener.uma_introspection_data_provider]
enable=true
```
